sodu: required
language: generic 
services:
  - docker

before_install:
  - docker build -t hujindi1212/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true hujindi1212/docker-react yarn test -- --coverage